# Generated by Django 6.0 on 2026-01-06 01:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 5, 20, 34, 2, 402771)),
        ),
    ]
