# Generated by Django 6.0 on 2026-01-09 00:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 8, 19, 59, 25, 333769)),
        ),
    ]
